trigger:
- main

strategy:
  matrix:
    jdk17_linux:
      imageName: "ubuntu-latest"
      jdkVersion: "1.17"
    jdk21_windows:
      imageName: "windows-latest"
      jdkVersion: "1.21"
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
- task: Maven@4
  inputs:
    mavenPomFile: "pom.xml"
    mavenOptions: "-Xmx3072m"
    javaHomeOption: "JDKVersion"
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: "**/TEST-*.xml"
    goals: "package"